### ISSUE TITLE
Requires a phone number

### ISSUE THREAD

**Issue by Lord-Dogbert** [SANdood/Home-on-Code-Unlock-Too#2]
Under notifications, a number must be present to proceed to the next screen. I entered a 1 to please it.

**Comment by SANdood** [comment]
To be honest, I have not been maintaining this code for quite some time. I now use RBoys' Lock Code Manager, as it is more versatile, supports multiple locks, and timed/temporary codes.

**Comment by Lord-Dogbert** [comment]
Cool. Thanks.
-------- Original message --------From: Barry Burke <notifications@github.com> Date: 1/21/18  5:03 AM  (GMT-08:00) To: SANdood/Home-on-Code-Unlock-Too <Home-on-Code-Unlock-Too@noreply.github.com> Cc: Lord-Dogbert <igmp2u@gmail.com>, Author <author@noreply.github.com> Subject: Re: [SANdood/Home-on-Code-Unlock-Too] Requires a phone number (#2) 
To be honest, I have not been maintaining this code for quite some time. I now use RBoys' Lock Code Manager, as it is more versatile, supports multiple locks, and timed/temporary codes.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/SANdood/Home-on-Code-Unlock-Too","title":"SANdood/Home-on-Code-Unlock-Too","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/SANdood/Home-on-Code-Unlock-Too"}},"updates":{"snippets":[{"icon":"PERSON","message":"@SANdood in #2: To be honest, I have not been maintaining this code for quite some time. I now use RBoys' Lock Code Manager, as it is more versatile, supports multiple locks, and timed/temporary codes."}],"action":{"name":"View Issue","url":"https://github.com/SANdood/Home-on-Code-Unlock-Too/issues/2#issuecomment-359246884"}}}
